language: script
script: "make travis"
env:
   global:
      - secure: "LeGSPFf50xSTI7rxlBACczat2Rso/8o2U1EdTCwvWA5qsSkUP9Xa3/QlUorrkZ0d8lbuTlOAoMkgZca5ZDtkGNrY5rSDgfsIorIqA+Vbtg5PKrKzzKqanawkC16piP1To/vs6bGFcN9WE3kFGzhsANNhoqMGVMaxmoxVyqCw4qA="
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install python-pip
   - sudo pip install xml2rfc
